# TODO: Replace the agent pool name
pool: myAgentPool

variables:
  # TODO: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'myServiceConnection'
  
  # TODO: Specify the value of the existing Web App name
  webAppName: 'webapp228983'
 
  # Environment name
  environmentName: 'Flask_ML_App'
  # Python version
  pythonVersion: '3.8'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: myAgentPool
    steps:    
    - script: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install setup
        python3.8 -m pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: 'myStep_1'
    - script: |
        export PATH=$HOME/.local/bin:$PATH
        make install
      workingDirectory: $(projectRoot)
      displayName: 'myStep_2'
    
    - task: ArchiveFiles@2
      displayName: 'myStep_3 - Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'myStep 5 - Upload package'
      artifact: drop
- stage: Deploy
  displayName: 'Deploy_myWebApp'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: myAgentPool
     
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : flask-sklearn'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip 
              deploymentMethod: zipDeploy